### ISSUE TITLE
Animation not working when assembleRelease

### ISSUE THREAD

**Issue by TurhanOz** [tajchert/WaitingDots#14]
Is there any proguard rules required ?
Cheers

**Comment by tajchert** [comment]
It shouldn't require any additional rules.

**Comment by TurhanOz** [comment]
for now, I have added theses rules to make it work (may not be the most effective though)
`
-dontwarn pl.tajchert.sample.**
-keep public class pl.tajchert.sample.** {
     public protected private *;
}
`

**Comment by tajchert** [comment]
Thanks, I will test this, and most likely add to README.

**Comment by tieorange** [comment]
@TurhanOz Thanks so much. It works on Nexus 5X Android 7.0 :)

**Comment by TurhanOz** [comment]
you're more than welcome :)

**Comment by aaronvargas** [comment]
Please, please add this to the README! I just spent a couple hours on this. Didn't realize the app I was working on had minimize enabled for debug due to size. Plus you're going to need it anyway once you make a release build, most likely.

**Comment by tajchert** [comment]
Thanks, I totally forgot about this one.

Added to Readme, update package name, bumped build tools version and released as 0.4.0 - enjoy!
