### ISSUE TITLE
Not working on API 22

### ISSUE THREAD

**Issue by vnh1991** [tajchert/WaitingDots#7]
Below attached is the code snippet

```
    private DotsTextView mLoadingDots;
@Override
protected void onCreate(Bundle savedInstanceState) {
    super.onCreate(savedInstanceState);
    setContentView(R.layout.activity_splash);
    mLoadingDots = (DotsTextView) findViewById(R.id.dots_text);     
    mLoadingDots.start();
            mLoadingDots.showAndPlay();
```

in my layout ive added

```
       <pl.tajchert.sample.DotsTextView
        android:layout_width="wrap_content"
        android:layout_height="wrap_content"
        android:id="@+id/dots_text"
        android:textSize="50sp"
        android:paddingBottom="10dp"
        android:layout_marginLeft="5dp"
        dots:autoplay="true"
        dots:period="250" />
```

in my build.grade
   dependencies { 
         compile 'pl.tajchert:waitingdots:0.2.0'
    }

changing to 0.1.0 gets it working but the animation is weird
it comes from left to right then starts jumping(lagging all the way)

tested on nexus 5 and moto g1 running 5.1

**Comment by vnh1991** [comment]
doesnt work on 6.0 too

**Comment by furkantektas** [comment]
I'm also experiencing the same issue on 6.0.1. 
v0.2.0 is not visible at all, yet v0.1.0 is visible but has laggy animation.

**Comment by martinflorek** [comment]
Anything new about this issue?

**Comment by dvdmunckhof** [comment]
Yes, I created a pull request with a workaround @martinflorek

**Comment by tajchert** [comment]
@Dennis123789 thanks! :+1:
