### ISSUE TITLE
android.view.WindowManager$BadTokenException: Unable to add window android.view.ViewRootImpl$W@a2cf037 -- permission denied for this window type

### ISSUE THREAD

**Issue by rakshitsoni02** [tajchert/WaitingDots#8]
getting this only on api 23 
 already added 
 <uses-permission android:name="android.permission.SYSTEM_ALERT_WINDOW"/>
    <uses-permission android:name="android.permission.TYPE_SYSTEM_OVERLAY"/>

**Comment by tajchert** [comment]
Hi,
Couldn't replicate problem, no exception or even a log value wasn't reported with "BadTokenException". Works fine for me. Please if issue persist - create sample project to replicate it and let me know - for now I close this issue.
